### ISSUE TITLE
Account Deletion Request

### ISSUE THREAD

**Issue by Anon3853** [webdestroya/sourcemod-translator#22]
I would like to have my account permanently closed and deleted. How can I achieve this?
There does not seem to be a way to do this via the interface and there is no contact email, privacy policy link or similar anywhere.

Perhaps you could manually handle the deletion, as a one-of task, @webdestroya?

**Comment by webdestroya** [comment]
You can email me your account info at `sourcemod -at- mitchdempsey.com` and I can replace your name/email with fake data.
